cc_library(
    name = "jconn",
    srcs = [
        "jconn.cpp",
    ],
    hdrs = [
        "jconn.hpp",
    ],
    deps = [
    ],
    copts = [
        "-std=c++20",
    ],
    linkopts = [
        "-lpthread",
    ],
    visibility = ["//visibility:public"],
)