cc_library(
    name = "jmutex",
    srcs = [
        "jmutex.cpp",
    ],
    hdrs = [
        "jmutex.hpp",
    ],
    deps = [
        "//util:jtime",
    ],
    copts = [],
    linkopts = [
        "-lpthread",
    ],
    visibility = ["//visibility:public"],
)